### ISSUE TITLE
Getting returned non-zero exit status 2 in ROUGUE-1.5.5.pl

### ISSUE THREAD

**Issue by lordzuko** [Wendy-Xiao/Extsumm_local_global_context#3]
@Wendy-Xiao I am trying to reproduce the results, but I am getting the following error, can you please guide me if I am missing something here?
```
 python test.py --train_input datasets/pubmed/inputs/train --train_label datasets/pubmed/labels/train --test_input datasets/pubmed/inputs/test --test_label datasets/pubmed/labels/test --refpath datasets/pubmed/human-abstracts/test --gloveDir embeddings --length_limit 200 --dataset Pubmed --device 0 --model attentive_context --model_path pretrained_models/Pubmed/attentive_context
Namespace(batchsize=32, cell='gru', dataset='Pubmed', device=0, embedding_dim=300, gloveDir='embeddings', hidden_dim=300, length_limit=200, mlp_size=100, model='attentive_context', model_path='pretrained_models/Pubmed/attentive_context', refpath='datasets/pubmed/human-abstracts/test', remove_stopwords=False, result_file_name=None, runtime=0, stemmer=False, test_file_list=None, test_input='datasets/pubmed/inputs/test', test_label='datasets/pubmed/labels/test', train_file_list=None, train_input='datasets/pubmed/inputs/train', train_label='datasets/pubmed/labels/train', vocab_size=50000)
Load vocabulary from vocabulary_Pubmed.json
Compute pos weight done! There are 4464502 sentences in total, with 203135 sentences as positive
Start loading model.
Start evaluating.
Batch 1, Loss: 1.053281
Can't locate XML/DOM.pm in @INC (you may need to install the XML::DOM module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.26.1 /usr/local/share/perl/5.26.1 /usr/lib/x86_64-linux-gnu/perl5/5.26 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.26 /usr/share/perl/5.26 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /Data/santosh_1821cs03/.cache/Python-Eggs/rouge_papier_v2-0.0.1-py3.7.egg-tmp/rouge_papier_v2/data/ROUGE-1.5.5.pl line 173.
BEGIN failed--compilation aborted at /Data/santosh_1821cs03/.cache/Python-Eggs/rouge_papier_v2-0.0.1-py3.7.egg-tmp/rouge_papier_v2/data/ROUGE-1.5.5.pl line 173.
Traceback (most recent call last):
  File "test.py", line 140, in <module>
    r2, l = eval_seq2seq(test_dataloader,model,hyp_path,LENGTH_LIMIT,pos_weight,device,USE_SECTION_INFO,remove_stopwords,stemmer,meteor=True,lcs=lcs,saveas=SAVE_RESULT_NAME)
  File "/Data/santosh_1821cs03/Santosh/Extractive-SUMM/extractive-summarization/run.py", line 86, in eval_seq2seq
    rouge2,df = get_rouge(summ_path, ref_path, length_limit,remove_stopwords,stemmer,lcs)
  File "/Data/santosh_1821cs03/Santosh/Extractive-SUMM/extractive-summarization/utils.py", line 98, in get_rouge
    remove_stopwords=remove_stopwords,stemmer=stemmer,set_length = False, length=length_limit)
  File "/Data/santosh_1821cs03/anaconda3/envs/extractive-summarization/lib/python3.7/site-packages/rouge_papier_v2-0.0.1-py3.7.egg/rouge_papier_v2/wrapper.py", line 61, in compute_rouge
  File "/Data/santosh_1821cs03/anaconda3/envs/extractive-summarization/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/Data/santosh_1821cs03/anaconda3/envs/extractive-summarization/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'perl /Data/santosh_1821cs03/.cache/Python-Eggs/rouge_papier_v2-0.0.1-py3.7.egg-tmp/rouge_papier_v2/data/ROUGE-1.5.5.pl -e /Data/santosh_1821cs03/.cache/Python-Eggs/rouge_papier_v2-0.0.1-py3.7.egg-tmp/rouge_papier_v2/rouge_data -a -n 2 -d -r 1000 -f A -z SPL ./config' returned non-zero exit status 2.

```

In the following command:

`perl /Data/santosh_1821cs03/.cache/Python-Eggs/rouge_papier_v2-0.0.1-py3.7.egg-tmp/rouge_papier_v2/data/ROUGE-1.5.5.pl -e /Data/santosh_1821cs03/.cache/Python-Eggs/rouge_papier_v2-0.0.1-py3.7.egg-tmp/rouge_papier_v2/rouge_data -a -n 2 -d -r 1000 -f A -z SPL ./config`

there is `./config` , what is this file ?

**Comment by lordzuko** [comment]
This was happening probably because of old version of Perl. Here is the solution: `perl -MCPAN -e 'install XML::DOM'`
For more details:
https://stackoverflow.com/questions/37591185/cant-locate-xml-dom-pm-in-inc-you-may-need-to-install-the-xmldom-module
